name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      E2E_KIND_CLUSTER_NUM: 4
      GO_VERSION: 1.16.15
      GOPATH: /home/circleci/go
      GOPROXY: https://proxy.golang.org
      PATH: /bin:/usr/bin:/usr/local/go/bin:/home/circleci/go/bin
    steps:
      - uses: actions/checkout@v3
      - name: Install Golang
        run: |
          curl -OL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
          tar -xf go${GO_VERSION}.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo mv go /usr/local
          mkdir -p "$HOME/go/bin"
          rm -rf go${GO_VERSION}.linux-amd64.tar.gz
          go version
      - name: Update packages
        timeout-minutes: 10
        run: |
          # Kill any apt-get processes that may be hanging due to
          # networking related issues, and thus holding on to
          # `/var/lib/apt/lists/lock`.
          # https://support.circleci.com/hc/en-us/articles/360021256633-Apt-Get-Update-Is-Slow-Or-Locked
          sudo killall apt-get || true

          sudo apt-get update
          sudo apt-get install jq
          git version
          docker version
          jq --version
      - run: make check-generated
      - run: make test TEST_FLAGS="-race -timeout 5m"
      - run: make all
      - name: End-to-end Helm v2
        run: make e2e
        env:
          HELM_VERSION: v2
      - name: End-to-end Helm v3
        run: make e2e
        env:
          HELM_VERSION: v3
